/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './__root'
import { Route as IndexRouteImport } from './index'
import { Route as CollectionIndexRouteImport } from './collection/index'
import { Route as ArtIdIndexRouteImport } from './art/$id/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionIndexRoute = CollectionIndexRouteImport.update({
  id: '/collection/',
  path: '/collection/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtIdIndexRoute = ArtIdIndexRouteImport.update({
  id: '/art/$id/',
  path: '/art/$id/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/collection': typeof CollectionIndexRoute
  '/art/$id': typeof ArtIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/collection': typeof CollectionIndexRoute
  '/art/$id': typeof ArtIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/collection/': typeof CollectionIndexRoute
  '/art/$id/': typeof ArtIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/collection' | '/art/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/collection' | '/art/$id'
  id: '__root__' | '/' | '/collection/' | '/art/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CollectionIndexRoute: typeof CollectionIndexRoute
  ArtIdIndexRoute: typeof ArtIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection/': {
      id: '/collection/'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof CollectionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/art/$id/': {
      id: '/art/$id/'
      path: '/art/$id'
      fullPath: '/art/$id'
      preLoaderRoute: typeof ArtIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CollectionIndexRoute: CollectionIndexRoute,
  ArtIdIndexRoute: ArtIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
